// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7CA7_aW72bBEX6qP_K7BKhW2rX3iP3iQ',
    appId: '1:311145878048:web:716ea120d6fb4b512de245',
    messagingSenderId: '311145878048',
    projectId: 'e-commerce-2a371',
    authDomain: 'e-commerce-2a371.firebaseapp.com',
    storageBucket: 'e-commerce-2a371.firebasestorage.app',
    measurementId: 'G-W6DDQLY9RR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_A6UmC0UAGhWi_JgHsot08D3ViY6vDiM',
    appId: '1:311145878048:android:3238447f245b9c972de245',
    messagingSenderId: '311145878048',
    projectId: 'e-commerce-2a371',
    storageBucket: 'e-commerce-2a371.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxKE7T2qs_c4ZHfTpDCnUgmQcwyA-XtX4',
    appId: '1:311145878048:ios:3c6e7148b24088f32de245',
    messagingSenderId: '311145878048',
    projectId: 'e-commerce-2a371',
    storageBucket: 'e-commerce-2a371.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxKE7T2qs_c4ZHfTpDCnUgmQcwyA-XtX4',
    appId: '1:311145878048:ios:3c6e7148b24088f32de245',
    messagingSenderId: '311145878048',
    projectId: 'e-commerce-2a371',
    storageBucket: 'e-commerce-2a371.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7CA7_aW72bBEX6qP_K7BKhW2rX3iP3iQ',
    appId: '1:311145878048:web:f53749db5af0a1232de245',
    messagingSenderId: '311145878048',
    projectId: 'e-commerce-2a371',
    authDomain: 'e-commerce-2a371.firebaseapp.com',
    storageBucket: 'e-commerce-2a371.firebasestorage.app',
    measurementId: 'G-J60XX887RE',
  );
}
